# -*- coding: utf-8 -*-
"""Total de horas aula na Alura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198RonHzXEWbd7HOcrfJcNoN-Ydy8YRk3

Web Scraping com BeautifulSoup e RegEx
"""

import bs4
import urllib.request as urllib_request

print("BeautifulSoup ->", bs4.__version__)
print("urllib ->", urllib_request.__version__)

from urllib.request import urlopen
from bs4 import BeautifulSoup

url = 'https://cursos.alura.com.br/user/patriciatayna/fullCertificate/9953f706cd263f4880765ccbb01ba635'

response = urlopen(url)
html = response.read()

soup = BeautifulSoup(html, 'html.parser')
#soup

import re
padrao = re.compile(r'([0-9]{1,2}hrs)')

string_soup = str(soup)

lista_horas = padrao.findall(string_soup)
#lista_horas

lista_com_numeros = []
for carga_horaria in lista_horas:
  lista_com_numeros.append(int(carga_horaria[:-3]))
#lista_com_numeros

soma = sum(lista_com_numeros)

print(f'Total de {len(lista_horas)} cursos concluídos, totalizando a carga horária estimada em {soma} horas')